CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Games" (
    "Id" bytea NOT NULL,
    "IsRunning" boolean NOT NULL,
    "CreatedAt" bigint NOT NULL,
    "ScenarioId" text NOT NULL,
    CONSTRAINT "PK_Games" PRIMARY KEY ("Id")
);

CREATE TABLE "LicenseSecrets" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Salt" text NOT NULL,
    "CreatedAt" text NOT NULL,
    CONSTRAINT "PK_LicenseSecrets" PRIMARY KEY ("Id")
);

CREATE TABLE "Media" (
    "MediaId" text NOT NULL,
    "Type" integer NOT NULL,
    "Url" text,
    "Content" text,
    "DelaySeconds" integer NOT NULL,
    "Duration" integer,
    "ShowOnPlayer" boolean NOT NULL,
    CONSTRAINT "PK_Media" PRIMARY KEY ("MediaId")
);

CREATE TABLE "Players" (
    "Id" bytea NOT NULL,
    "Nickname" character varying(255) NOT NULL,
    CONSTRAINT "PK_Players" PRIMARY KEY ("Id")
);

CREATE TABLE "RoundTypes" (
    "RoundTypeId" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "RoundClass" integer NOT NULL,
    "WaitingRoundTimeout" boolean NOT NULL,
    "DisplayQuestionOnInformator" boolean NOT NULL,
    "DisplayQuestionOnPlayers" boolean NOT NULL,
    CONSTRAINT "PK_RoundTypes" PRIMARY KEY ("RoundTypeId")
);

CREATE TABLE "Scenarios" (
    "Id" text NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "GameDuration" integer,
    "BasePointPrice" integer NOT NULL,
    "StartPlayerScore" integer NOT NULL,
    "RoundPresentationDuration" integer,
    "ShowScenarioStatsOnFinish" boolean NOT NULL,
    "FinishPlaceholder" text,
    "Placeholder" text NOT NULL,
    CONSTRAINT "PK_Scenarios" PRIMARY KEY ("Id")
);

CREATE TABLE "Licenses" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LicenseKey" text NOT NULL,
    "ExpirationTime" text NOT NULL,
    "GamesLeft" text NOT NULL,
    "Active" boolean NOT NULL,
    "SaltId" bigint NOT NULL,
    CONSTRAINT "PK_Licenses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Licenses_LicenseSecrets_SaltId" FOREIGN KEY ("SaltId") REFERENCES "LicenseSecrets" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Localizations" (
    "Id" bytea NOT NULL,
    "ScenarioId" text NOT NULL,
    "ButtonUp" text NOT NULL,
    "ButtonDown" text NOT NULL,
    "ButtonConfirm" text NOT NULL,
    "ButtonCancel" text NOT NULL,
    "ButtonContinue" text NOT NULL,
    "ButtonBuy" text NOT NULL,
    "ButtonFinish" text NOT NULL,
    "ButtonStub" text NOT NULL,
    "BidButtonLabel" text NOT NULL,
    "AttentionLabel" text NOT NULL,
    "WaitOtherPlayersLabel" text NOT NULL,
    "WaitYourTurnLabel" text NOT NULL,
    "HintLabel" text NOT NULL,
    "SpeedWinnerLabel" text NOT NULL,
    "PantomimeLabel" text NOT NULL,
    "VotingLabel" text NOT NULL,
    "PlayerLabel" text NOT NULL,
    "ScoreLabel" text NOT NULL,
    "BetTime" text NOT NULL,
    "MakeBetLabelPart1" text NOT NULL,
    "MakeBetLabelPart2" text NOT NULL,
    "BidAcceptedLabelPart1" text NOT NULL,
    "BidAcceptedLabelPart2" text NOT NULL,
    "PriceLabel" text NOT NULL,
    "LoginLabel" text NOT NULL,
    "RoundLabel" text NOT NULL,
    "RoundResultsLabel" text NOT NULL,
    "RoundChoiceLabel" text NOT NULL,
    "ShopLabel" text NOT NULL,
    "InsufficientFunds" text NOT NULL,
    "ProductHasBeenPurchased" text NOT NULL,
    "ProductAlreadyPurchased" text NOT NULL,
    "ShopWaitLabel" text NOT NULL,
    "ApplyingModifiersLabel" text NOT NULL,
    "GameFinishLabel" text NOT NULL,
    CONSTRAINT "PK_Localizations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Localizations_Scenarios_ScenarioId" FOREIGN KEY ("ScenarioId") REFERENCES "Scenarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Rounds" (
    "RoundId" text NOT NULL,
    "ScenarioId" text NOT NULL,
    "RoundTypeId" integer NOT NULL,
    "Name" text,
    "Description" text,
    "PreviewUrl" text,
    "RoundDuration" integer,
    "CorrectMultiplier" integer NOT NULL,
    "MissedMultiplier" integer NOT NULL,
    "IncorrectMultiplier" integer NOT NULL,
    CONSTRAINT "PK_Rounds" PRIMARY KEY ("RoundId"),
    CONSTRAINT "FK_Rounds_RoundTypes_RoundTypeId" FOREIGN KEY ("RoundTypeId") REFERENCES "RoundTypes" ("RoundTypeId") ON DELETE CASCADE,
    CONSTRAINT "FK_Rounds_Scenarios_ScenarioId" FOREIGN KEY ("ScenarioId") REFERENCES "Scenarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ScenarioStatistics" (
    "Id" bytea NOT NULL,
    "GameId" bytea NOT NULL,
    "PlayerId" bytea NOT NULL,
    "ScenarioId" text NOT NULL,
    "Score" integer NOT NULL,
    CONSTRAINT "PK_ScenarioStatistics" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ScenarioStatistics_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ScenarioStatistics_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ScenarioStatistics_Scenarios_ScenarioId" FOREIGN KEY ("ScenarioId") REFERENCES "Scenarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Stocks" (
    "Id" bytea NOT NULL,
    "ScenarioId" text NOT NULL,
    "ModifierType" integer NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "IconUrl" text NOT NULL,
    "Quantity" integer NOT NULL,
    "CostMultiplier" integer NOT NULL,
    "UniqForPlayer" boolean NOT NULL,
    CONSTRAINT "PK_Stocks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Stocks_Scenarios_ScenarioId" FOREIGN KEY ("ScenarioId") REFERENCES "Scenarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Questions" (
    "Id" bytea NOT NULL,
    "RoundId" text NOT NULL,
    "QuestionNumber" integer NOT NULL,
    "QuestionText" text NOT NULL,
    "MediaId" text,
    "AnswerDelay" integer,
    "QuestionTimeout" integer NOT NULL,
    CONSTRAINT "PK_Questions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Questions_Media_MediaId" FOREIGN KEY ("MediaId") REFERENCES "Media" ("MediaId") ON DELETE CASCADE,
    CONSTRAINT "FK_Questions_Rounds_RoundId" FOREIGN KEY ("RoundId") REFERENCES "Rounds" ("RoundId") ON DELETE CASCADE
);

CREATE TABLE "RoundStatistics" (
    "Id" bytea NOT NULL,
    "GameId" bytea NOT NULL,
    "PlayerId" bytea NOT NULL,
    "RoundId" text NOT NULL,
    "Score" integer NOT NULL,
    CONSTRAINT "PK_RoundStatistics" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoundStatistics_Games_GameId" FOREIGN KEY ("GameId") REFERENCES "Games" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RoundStatistics_Players_PlayerId" FOREIGN KEY ("PlayerId") REFERENCES "Players" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RoundStatistics_Rounds_RoundId" FOREIGN KEY ("RoundId") REFERENCES "Rounds" ("RoundId") ON DELETE CASCADE
);

CREATE TABLE "Stages" (
    "Id" bytea NOT NULL,
    "ScenarioId" text NOT NULL,
    "Index" integer NOT NULL,
    "Type" integer NOT NULL,
    "MediaId" text,
    "RoundId" text,
    "StageDuration" integer,
    CONSTRAINT "PK_Stages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Stages_Media_MediaId" FOREIGN KEY ("MediaId") REFERENCES "Media" ("MediaId") ON DELETE CASCADE,
    CONSTRAINT "FK_Stages_Rounds_RoundId" FOREIGN KEY ("RoundId") REFERENCES "Rounds" ("RoundId") ON DELETE CASCADE,
    CONSTRAINT "FK_Stages_Scenarios_ScenarioId" FOREIGN KEY ("ScenarioId") REFERENCES "Scenarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Answers" (
    "Id" bytea NOT NULL,
    "QuestionId" bytea NOT NULL,
    "Text" text NOT NULL,
    "Button" text NOT NULL,
    "IsCorrect" boolean,
    "Order" integer,
    CONSTRAINT "PK_Answers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Answers_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Hints" (
    "Id" bytea NOT NULL,
    "QuestionId" bytea NOT NULL,
    "Text" text NOT NULL,
    CONSTRAINT "PK_Hints" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Hints_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Reveals" (
    "Id" bytea NOT NULL,
    "QuestionId" bytea NOT NULL,
    "MediaId" text,
    "Text" text NOT NULL,
    "Duration" integer NOT NULL,
    CONSTRAINT "PK_Reveals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reveals_Media_MediaId" FOREIGN KEY ("MediaId") REFERENCES "Media" ("MediaId") ON DELETE CASCADE,
    CONSTRAINT "FK_Reveals_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Answers_QuestionId" ON "Answers" ("QuestionId");

CREATE INDEX "IX_Hints_QuestionId" ON "Hints" ("QuestionId");

CREATE UNIQUE INDEX "IX_Licenses_SaltId" ON "Licenses" ("SaltId");

CREATE UNIQUE INDEX "IX_Localizations_ScenarioId" ON "Localizations" ("ScenarioId");

CREATE UNIQUE INDEX "IX_Players_Nickname" ON "Players" ("Nickname");

CREATE INDEX "IX_Questions_MediaId" ON "Questions" ("MediaId");

CREATE INDEX "IX_Questions_RoundId" ON "Questions" ("RoundId");

CREATE INDEX "IX_Reveals_MediaId" ON "Reveals" ("MediaId");

CREATE UNIQUE INDEX "IX_Reveals_QuestionId" ON "Reveals" ("QuestionId");

CREATE INDEX "IX_Rounds_RoundTypeId" ON "Rounds" ("RoundTypeId");

CREATE INDEX "IX_Rounds_ScenarioId" ON "Rounds" ("ScenarioId");

CREATE INDEX "IX_RoundStatistics_GameId" ON "RoundStatistics" ("GameId");

CREATE INDEX "IX_RoundStatistics_PlayerId" ON "RoundStatistics" ("PlayerId");

CREATE INDEX "IX_RoundStatistics_RoundId" ON "RoundStatistics" ("RoundId");

CREATE INDEX "IX_ScenarioStatistics_GameId" ON "ScenarioStatistics" ("GameId");

CREATE INDEX "IX_ScenarioStatistics_PlayerId" ON "ScenarioStatistics" ("PlayerId");

CREATE INDEX "IX_ScenarioStatistics_ScenarioId" ON "ScenarioStatistics" ("ScenarioId");

CREATE INDEX "IX_Stages_MediaId" ON "Stages" ("MediaId");

CREATE INDEX "IX_Stages_RoundId" ON "Stages" ("RoundId");

CREATE INDEX "IX_Stages_ScenarioId" ON "Stages" ("ScenarioId");

CREATE INDEX "IX_Stocks_ScenarioId" ON "Stocks" ("ScenarioId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250729203740_Initial', '9.0.4');

COMMIT;

